on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # Build inside Docker containers (includes installing dependencies)
      - name: Build with SAM
        run: sam build --use-container

      # Run the tests (after dependencies are installed by SAM build)
      - name: Run tests
        run: |
          cd .aws-sam/build
          pip3 install pytest
          python3 -m pytest -s -v

      # Deploy the stack if tests pass
      - name: Deploy with SAM
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --template-file template.yaml --stack-name CodeQuestStack
